FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash paladeum

RUN mkdir /etc/paladeum

RUN mkdir /var/lib/paladeum

RUN chown paladeum:paladeum /etc/paladeum /var/lib/paladeum

WORKDIR /home/paladeum

COPY --chown=paladeum:paladeum linux64/* ./run.sh /home/paladeum/

USER paladeum

CMD ["/home/paladeum/run.sh"]
