FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash akila

RUN mkdir /etc/akila

RUN mkdir /var/lib/akila

RUN chown akila:akila /etc/akila /var/lib/akila

WORKDIR /home/akila

COPY --chown=akila:akila linux64/* /home/akila/

COPY --chown=akila:akila run.sh /home/akila/

USER akila

CMD ["/home/akila/run.sh"]
