FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash akila

RUN mkdir /etc/akila

RUN mkdir /var/lib/akila

RUN chown akila:akila /etc/akila /var/lib/akila

WORKDIR /home/akila

COPY --chown=akila:akila linux64/* ./run.sh /home/akila/

USER akila

CMD ["/home/akila/run.sh"]
